services:
  igpublisher:
    build: .
    image: ghcr.io/syndael/coleccion-igpublisher:latest
    container_name: igpublisher
    restart: unless-stopped
    volumes:
      - /volume1/ProgramacionNas/Coleccion/IgPublisher/config.txt:/app/config.txt:ro
      - /volume1/ProgramacionNas/Coleccion/IgPublisher/ig_session.json:/app/ig_session.json
      - /volume1/ProgramacionNas/Coleccion/IgPublisher/music:/app/music
      - /volume1/ProgramacionNas/Coleccion/IgPublisher/gif:/app/gif
      - /volume1/ProgramacionNas/Coleccion/IgPublisher/dev_output:/app/dev_output
    environment:
      - TZ=Europe/Madrid
