/*
	SELECT * FROM ESTADO ORDER BY TIPO, DESCRIPCION
	SELECT * FROM JUEGO WHERE NOMBRE LIKE '%harry%'
	SELECT * FROM PLATAFORMA
	SELECT * FROM IDIOMA
	SELECT * FROM REGION
	SELECT * FROM TIENDA
	SELECT * FROM V_COLECCION_POKE ORDER BY id desc
*/

SET @n_juego = 'Harry Potter and the Chamber of Secrets'; SELECT * FROM JUEGO WHERE NOMBRE = @n_juego;
SET @plata = 'GBC'; SELECT * FROM PLATAFORMA WHERE COALESCE(CORTO, NOMBRE) = @plata;
SET @d_idioma = 'Español'; SELECT * FROM IDIOMA WHERE DESCRIPCION = @d_idioma;
SET @d_region = 'EU'; SELECT * FROM REGION WHERE CORTO = @d_region;
SET @estado_gen = 'Completo'; SELECT * FROM ESTADO WHERE DESCRIPCION = @estado_gen AND TIPO = 0;
-- 'Mal' 'Bien' 'Perfecta'
SET @estado_caja = 'Bien'; SELECT * FROM ESTADO WHERE DESCRIPCION = @estado_caja AND TIPO = 1;
SET @n_tienda = 'Wallapop'; SELECT * FROM TIENDA WHERE NOMBRE = @n_tienda;
SET @f_compra = '20230715';
SET @f_recibo = NULL;
SET @coste = 36.43;
SET @notas = NULL;

INSERT INTO COLECCION (
    JUEGO_ID, PLATAFORMA_ID, IDIOMA_ID, REGION_ID, ESTADO_GENERAL_ID, ESTADO_CAJA_ID,
    FECHA_COMPRA, FECHA_RECIBO, COSTE, TIENDA_ID, NOTAS
) SELECT 
    (SELECT ID FROM JUEGO WHERE NOMBRE = @n_juego),
    (SELECT ID FROM PLATAFORMA WHERE COALESCE(CORTO, NOMBRE) = @plata),
    (SELECT ID FROM IDIOMA WHERE DESCRIPCION = @d_idioma),
    (SELECT ID FROM REGION WHERE CORTO = @d_region),
    (SELECT ID FROM ESTADO WHERE DESCRIPCION = @estado_gen AND TIPO = 0),
    (SELECT ID FROM ESTADO WHERE DESCRIPCION = @estado_caja AND TIPO = 1),
    @f_compra, @f_recibo, @coste,
    (SELECT ID FROM TIENDA WHERE NOMBRE = @n_tienda),
    @notas
FROM DUAL WHERE NOT EXISTS (
	SELECT 1 FROM COLECCION WHERE
		JUEGO_ID = (SELECT ID FROM JUEGO WHERE NOMBRE = @n_juego)
		AND PLATAFORMA_ID = (SELECT ID FROM PLATAFORMA WHERE COALESCE(CORTO, NOMBRE) = @plata)
		AND IDIOMA_ID = (SELECT ID FROM IDIOMA WHERE DESCRIPCION = @d_idioma)
		AND ESTADO_GENERAL_ID = (SELECT ID FROM ESTADO WHERE DESCRIPCION = @estado_gen AND TIPO = 0)
		AND ESTADO_CAJA_ID = (SELECT ID FROM ESTADO WHERE DESCRIPCION = @estado_caja AND TIPO = 1)
		AND FECHA_COMPRA = @f_compra
		AND COSTE = @coste
);

SELECT * FROM V_COLECCION_POKE ORDER BY ID DESC LIMIT 10;