/*
	SELECT * FROM ESTADO ORDER BY TIPO, DESCRIPCION
	SELECT * FROM JUEGO WHERE NOMBRE LIKE '%cult%'
	SELECT * FROM PLATAFORMA
	SELECT * FROM IDIOMA
	SELECT * FROM REGION
	SELECT * FROM TIENDA
	SELECT * FROM V_COLECCION_POKE ORDER BY id desc
*/

SET @n_juego = 'Cult of the Lamb'; SELECT * FROM JUEGO WHERE NOMBRE = @n_juego;
SET @plata = 'Switch'; SELECT * FROM PLATAFORMA WHERE COALESCE(CORTO, NOMBRE) = @plata;
SET @estado_jugado = 'Terminado'; SELECT * FROM ESTADO WHERE DESCRIPCION = @estado_gen AND TIPO = 2;
SET @porcentaje = 75;
SET @horas = 27;
SET @completo = 1;
SET @notas = NULL;
SET @f_ini = NULL;
SET @f_fin = '20230716';

INSERT INTO JUGADO (
    JUEGO_ID, PLATAFORMA_ID, ESTADO_JUGADO_ID, PORCENTAJE,
	 HORAS, HISTORIA_COMPLETA, NOTAS, FECHA_INCIO, FECHA_FIN
) VALUES ( 
    (SELECT ID FROM JUEGO WHERE NOMBRE = @n_juego),
    (SELECT ID FROM PLATAFORMA WHERE COALESCE(CORTO, NOMBRE) = @plata),
    (SELECT ID FROM ESTADO WHERE DESCRIPCION = @estado_jugado AND TIPO = 2),
    @porcentaje, @horas, @completo, @notas, @f_ini, @f_fin
);

SELECT * FROM JUGADO ORDER BY ID DESC LIMIT 10;