-- --------------------------------------------------------
-- Host:                         192.168.1.55
-- Versión del servidor:         10.3.32-MariaDB - Source distribution
-- SO del servidor:              Linux
-- HeidiSQL Versión:             12.5.0.6677
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para coleccion
CREATE DATABASE IF NOT EXISTS `coleccion` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `coleccion`;

-- Volcando estructura para tabla coleccion.COLECCION
CREATE TABLE IF NOT EXISTS `COLECCION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `JUEGO_ID` int(11) NOT NULL,
  `PLATAFORMA_ID` int(11) NOT NULL,
  `IDIOMA_ID` int(11) DEFAULT NULL,
  `REGION_ID` int(11) DEFAULT NULL,
  `ESTADO_GENERAL_ID` int(11) NOT NULL,
  `ESTADO_CAJA_ID` int(11) NOT NULL,
  `FECHA_COMPRA` date DEFAULT NULL,
  `FECHA_RECIBO` date DEFAULT NULL,
  `COSTE` decimal(20,6) DEFAULT NULL,
  `TIENDA_ID` int(11) DEFAULT NULL,
  `NOTAS` varchar(500) DEFAULT NULL,
  `FECHA_INS` datetime DEFAULT current_timestamp(),
  `ACTIVADO` bit(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`ID`),
  KEY `JUEGO_ID_C_FK` (`JUEGO_ID`),
  KEY `PLATAFORMA_ID_C_FK` (`PLATAFORMA_ID`),
  KEY `IDIOMA_ID_C_FK` (`IDIOMA_ID`),
  KEY `REGION_ID_C_FK` (`REGION_ID`),
  KEY `ESTADO_GEN_ID_C_FK` (`ESTADO_GENERAL_ID`),
  KEY `TIENDA_ID_C_FK` (`TIENDA_ID`),
  KEY `ESTADO_CAJ_ID_C_FK` (`ESTADO_CAJA_ID`),
  CONSTRAINT `ESTADO_CAJ_ID_C_FK` FOREIGN KEY (`ESTADO_CAJA_ID`) REFERENCES `ESTADO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ESTADO_GEN_ID_C_FK` FOREIGN KEY (`ESTADO_GENERAL_ID`) REFERENCES `ESTADO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `IDIOMA_ID_C_FK` FOREIGN KEY (`IDIOMA_ID`) REFERENCES `IDIOMA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `JUEGO_ID_C_FK` FOREIGN KEY (`JUEGO_ID`) REFERENCES `JUEGO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PLATAFORMA_ID_C_FK` FOREIGN KEY (`PLATAFORMA_ID`) REFERENCES `PLATAFORMA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REGION_ID_C_FK` FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `TIENDA_ID_C_FK` FOREIGN KEY (`TIENDA_ID`) REFERENCES `TIENDA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=471 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.ESTADO
CREATE TABLE IF NOT EXISTS `ESTADO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(50) NOT NULL,
  `TIPO` int(11) NOT NULL COMMENT '0 General, 1 Cajas, 2 Jugado',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.IDIOMA
CREATE TABLE IF NOT EXISTS `IDIOMA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(50) NOT NULL,
  `CORTO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DESC_CORTO_I_UK` (`DESCRIPCION`,`CORTO`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.JUEGO
CREATE TABLE IF NOT EXISTS `JUEGO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `CODIGO` varchar(255) DEFAULT NULL,
  `SAGA` varchar(255) DEFAULT NULL,
  `FECHA_SALIDA` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOMBRE_SALIDA_JUEGO_UK` (`NOMBRE`,`FECHA_SALIDA`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=444 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.JUEGO_X_PLATAFORMA
CREATE TABLE IF NOT EXISTS `JUEGO_X_PLATAFORMA` (
  `JUEGO_ID` int(11) NOT NULL,
  `PLATAFORMA_ID` int(11) NOT NULL,
  PRIMARY KEY (`JUEGO_ID`,`PLATAFORMA_ID`),
  KEY `PLAT_ID_JXP_FK` (`PLATAFORMA_ID`),
  CONSTRAINT `JUEGO_ID_JXP_FK` FOREIGN KEY (`JUEGO_ID`) REFERENCES `JUEGO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PLAT_ID_JXP_FK` FOREIGN KEY (`PLATAFORMA_ID`) REFERENCES `PLATAFORMA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.JUGADO
CREATE TABLE IF NOT EXISTS `JUGADO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `JUEGO_ID` int(11) NOT NULL,
  `PLATAFORMA_ID` int(11) DEFAULT NULL,
  `ESTADO_JUGADO_ID` int(11) NOT NULL,
  `PORCENTAJE` int(11) DEFAULT NULL,
  `HORAS` decimal(20,6) DEFAULT NULL,
  `HISTORIA_COMPLETA` bit(1) DEFAULT NULL,
  `NOTAS` varchar(500) DEFAULT NULL,
  `FECHA_INICIO` date DEFAULT NULL,
  `FECHA_FIN` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `JUEGO_ID_J_FK` (`JUEGO_ID`),
  KEY `PLAT_ID_J_FK` (`PLATAFORMA_ID`),
  KEY `ESTADO_J_FK` (`ESTADO_JUGADO_ID`),
  CONSTRAINT `ESTADO_J_FK` FOREIGN KEY (`ESTADO_JUGADO_ID`) REFERENCES `ESTADO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `JUEGO_ID_J_FK` FOREIGN KEY (`JUEGO_ID`) REFERENCES `JUEGO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PLAT_ID_J_FK` FOREIGN KEY (`PLATAFORMA_ID`) REFERENCES `PLATAFORMA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.PLATAFORMA
CREATE TABLE IF NOT EXISTS `PLATAFORMA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `CORTO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOMBRE_PLAT_UK` (`NOMBRE`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.REGION
CREATE TABLE IF NOT EXISTS `REGION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(50) NOT NULL,
  `CORTO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `DESC_CORTO_R_UK` (`DESCRIPCION`,`CORTO`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.ROM
CREATE TABLE IF NOT EXISTS `ROM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `JUEGO_ID` int(11) NOT NULL,
  `PLATAFORMA_ID` int(11) DEFAULT NULL,
  `NOMBRE_ROM` varchar(255) DEFAULT NULL,
  `NOMBRE_ROM_EXT` varchar(255) DEFAULT NULL,
  `IDIOMA_ID` int(11) DEFAULT NULL,
  `REGION_ID` int(11) DEFAULT NULL,
  `TIPO_ROM_ID` int(11) DEFAULT NULL,
  `FECHA_DESCARGA` date DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `JUEGO_ID_R_FK` (`JUEGO_ID`),
  KEY `PLAT_ID_R_FK` (`PLATAFORMA_ID`),
  KEY `IDIOMA_ID_R_FK` (`IDIOMA_ID`),
  KEY `REGION_ID_R_FK` (`REGION_ID`),
  KEY `TIPO_ROM_ID_R_FK` (`TIPO_ROM_ID`),
  CONSTRAINT `IDIOMA_ID_R_FK` FOREIGN KEY (`IDIOMA_ID`) REFERENCES `IDIOMA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `JUEGO_ID_R_FK` FOREIGN KEY (`JUEGO_ID`) REFERENCES `JUEGO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PLAT_ID_R_FK` FOREIGN KEY (`PLATAFORMA_ID`) REFERENCES `PLATAFORMA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `REGION_ID_R_FK` FOREIGN KEY (`REGION_ID`) REFERENCES `REGION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `TIPO_ROM_ID_R_FK` FOREIGN KEY (`TIPO_ROM_ID`) REFERENCES `TIPO_ROM` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=761 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.TIENDA
CREATE TABLE IF NOT EXISTS `TIENDA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para tabla coleccion.TIPO_ROM
CREATE TABLE IF NOT EXISTS `TIPO_ROM` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXTENSION` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.

-- Volcando estructura para vista coleccion.V_COLECCION_POKE
-- Creando tabla temporal para superar errores de dependencia de VIEW
CREATE TABLE `V_COLECCION_POKE` (
	`ID` INT(11) NOT NULL,
	`Plataforma` VARCHAR(255) NULL COLLATE 'utf8_general_ci',
	`Saga` VARCHAR(255) NULL COLLATE 'utf8_general_ci',
	`Juego` VARCHAR(255) NOT NULL COLLATE 'utf8_general_ci',
	`Idioma` VARCHAR(50) NULL COLLATE 'utf8_general_ci',
	`Region` VARCHAR(50) NULL COLLATE 'utf8_general_ci',
	`EstadoGen` VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`EstadoCaj` VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`Compra` DATE NULL,
	`Recibido` DATE NULL,
	`Coste` DECIMAL(20,6) NULL,
	`Tienda` VARCHAR(50) NULL COLLATE 'utf8_general_ci',
	`Notas` VARCHAR(500) NULL COLLATE 'utf8_general_ci'
) ENGINE=MyISAM;

-- Volcando estructura para disparador coleccion.SET_CODIGO_JUEGO_ON_INSERT
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER SET_CODIGO_JUEGO_ON_INSERT
BEFORE INSERT ON JUEGO
FOR EACH ROW
BEGIN
	SET NEW.CODIGO = REGEXP_REPLACE(
		REPLACE(
			REPLACE(
				REPLACE(
					REPLACE(
						REPLACE(
							NEW.NOMBRE, 'ú', 'u'
						), 'ó', 'o'
					), 'í', 'i'
				), 'é', 'e'
			), 'á', 'a'
		), '[^a-zA-Z0-9]', ''
	);
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador coleccion.SET_CODIGO_JUEGO_ON_UPDATE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER SET_CODIGO_JUEGO_ON_UPDATE
BEFORE UPDATE ON JUEGO
FOR EACH ROW
BEGIN
	SET NEW.CODIGO = REGEXP_REPLACE(
		REPLACE(
			REPLACE(
				REPLACE(
					REPLACE(
						REPLACE(
							NEW.NOMBRE, 'ú', 'u'
						), 'ó', 'o'
					), 'í', 'i'
				), 'é', 'e'
			), 'á', 'a'
		), '[^a-zA-Z0-9]', ''
	);
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador coleccion.SET_NOMBRE_ROM_ON_INSERT
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `SET_NOMBRE_ROM_ON_INSERT` BEFORE INSERT ON `ROM` FOR EACH ROW BEGIN
	SET NEW.NOMBRE_ROM_EXT = CONCAT(
		(SELECT CODIGO FROM JUEGO WHERE ID = NEW.JUEGO_ID),
		COALESCE(CONCAT('_', (SELECT CORTO FROM IDIOMA WHERE ID = NEW.IDIOMA_ID)), ''),
		COALESCE(CONCAT('_', (SELECT CORTO FROM REGION WHERE ID = NEW.REGION_ID)), ''),
		COALESCE(CONCAT('.', (SELECT EXTENSION FROM TIPO_ROM WHERE ID = NEW.TIPO_ROM_ID)), '')
	);
	
	SET NEW.NOMBRE_ROM = CONCAT(
		(SELECT CODIGO FROM JUEGO WHERE ID = NEW.JUEGO_ID),
		COALESCE(CONCAT('_', (SELECT CORTO FROM IDIOMA WHERE ID = NEW.IDIOMA_ID)), ''),
		COALESCE(CONCAT('_', (SELECT CORTO FROM REGION WHERE ID = NEW.REGION_ID)), '')
	);
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador coleccion.SET_NOMBRE_ROM_ON_UPDATE
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `SET_NOMBRE_ROM_ON_UPDATE` BEFORE UPDATE ON `ROM` FOR EACH ROW BEGIN
	SET NEW.NOMBRE_ROM_EXT = CONCAT(
		(SELECT CODIGO FROM JUEGO WHERE ID = NEW.JUEGO_ID),
		COALESCE(CONCAT('_', (SELECT CORTO FROM IDIOMA WHERE ID = NEW.IDIOMA_ID)), ''),
		COALESCE(CONCAT('_', (SELECT CORTO FROM REGION WHERE ID = NEW.REGION_ID)), ''),
		COALESCE(CONCAT('.', (SELECT EXTENSION FROM TIPO_ROM WHERE ID = NEW.TIPO_ROM_ID)), '')
	);
	
	SET NEW.NOMBRE_ROM = CONCAT(
		(SELECT CODIGO FROM JUEGO WHERE ID = NEW.JUEGO_ID),
		COALESCE(CONCAT('_', (SELECT CORTO FROM IDIOMA WHERE ID = NEW.IDIOMA_ID)), ''),
		COALESCE(CONCAT('_', (SELECT CORTO FROM REGION WHERE ID = NEW.REGION_ID)), '')
	);
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para vista coleccion.V_COLECCION_POKE
-- Eliminando tabla temporal y crear estructura final de VIEW
DROP TABLE IF EXISTS `V_COLECCION_POKE`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `V_COLECCION_POKE` AS select `c`.`ID` AS `ID`,coalesce(`p`.`CORTO`,`p`.`NOMBRE`) AS `Plataforma`,`j`.`SAGA` AS `Saga`,`j`.`NOMBRE` AS `Juego`,`i`.`CORTO` AS `Idioma`,`r`.`CORTO` AS `Region`,`eg`.`DESCRIPCION` AS `EstadoGen`,`ec`.`DESCRIPCION` AS `EstadoCaj`,`c`.`FECHA_COMPRA` AS `Compra`,`c`.`FECHA_RECIBO` AS `Recibido`,`c`.`COSTE` AS `Coste`,`t`.`NOMBRE` AS `Tienda`,`c`.`NOTAS` AS `Notas` from (((((((`COLECCION` `c` join `PLATAFORMA` `p` on(`p`.`ID` = `c`.`PLATAFORMA_ID`)) join `JUEGO` `j` on(`j`.`ID` = `c`.`JUEGO_ID`)) left join `IDIOMA` `i` on(`i`.`ID` = `c`.`IDIOMA_ID`)) left join `REGION` `r` on(`r`.`ID` = `c`.`REGION_ID`)) join `ESTADO` `eg` on(`eg`.`ID` = `c`.`ESTADO_GENERAL_ID`)) join `ESTADO` `ec` on(`ec`.`ID` = `c`.`ESTADO_CAJA_ID`)) left join `TIENDA` `t` on(`t`.`ID` = `c`.`TIENDA_ID`)) order by `p`.`NOMBRE`,case when `j`.`SAGA` = 'Pokémon' then `j`.`FECHA_SALIDA` else 1 end,`j`.`NOMBRE`;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
