RENAME TABLE `JUGADO` TO `PROGRESO`;
ALTER TABLE `PROGRESO`
	DROP FOREIGN KEY `ESTADO_J_FK`;
ALTER TABLE `PROGRESO`
	CHANGE COLUMN `ESTADO_JUGADO_ID` `ESTADO_PROGRESO_ID` INT(11) NOT NULL AFTER `PLATAFORMA_ID`,
	DROP INDEX `ESTADO_J_FK`,
	ADD INDEX `ESTADO_J_FK` (`ESTADO_PROGRESO_ID`) USING BTREE,
	ADD CONSTRAINT `ESTADO_J_FK` FOREIGN KEY (`ESTADO_PROGRESO_ID`) REFERENCES `ESTADO` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;

RENAME TABLE `JUEGO` TO `BASE`;
RENAME TABLE `JUEGO_X_PLATAFORMA` TO `BASE_X_PLATAFORMA`;
ALTER TABLE `BASE`
	DROP INDEX `NOMBRE_SALIDA_JUEGO_UK`;

ALTER TABLE `BASE_X_PLATAFORMA`
	DROP FOREIGN KEY `JUEGO_ID_JXP_FK`;
ALTER TABLE `BASE_X_PLATAFORMA`
	CHANGE COLUMN `JUEGO_ID` `BASE_ID` INT(11) NOT NULL FIRST,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`BASE_ID`, `PLATAFORMA_ID`) USING BTREE,
	ADD CONSTRAINT `BASE_ID_JXP_FK` FOREIGN KEY (`BASE_ID`) REFERENCES `BASE` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `COLECCION`
	DROP FOREIGN KEY `JUEGO_ID_C_FK`;
ALTER TABLE `COLECCION`
	CHANGE COLUMN `JUEGO_ID` `BASE_ID` INT(11) NOT NULL AFTER `ID`,
	DROP INDEX `JUEGO_ID_C_FK`,
	ADD INDEX `BASE_ID_C_FK` (`BASE_ID`) USING BTREE,
	ADD CONSTRAINT `BASE_ID_C_FK` FOREIGN KEY (`BASE_ID`) REFERENCES `BASE` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `PROGRESO`
	DROP FOREIGN KEY `JUEGO_ID_J_FK`;
ALTER TABLE `PROGRESO`
	CHANGE COLUMN `JUEGO_ID` `BASE_ID` INT(11) NOT NULL AFTER `ID`,
	DROP INDEX `JUEGO_ID_J_FK`,
	ADD INDEX `BASE_ID_J_FK` (`BASE_ID`) USING BTREE,
	ADD CONSTRAINT `BASE_ID_J_FK` FOREIGN KEY (`BASE_ID`) REFERENCES `BASE` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;
	
ALTER TABLE `ROM`
	DROP FOREIGN KEY `JUEGO_ID_R_FK`;
ALTER TABLE `ROM`
	CHANGE COLUMN `JUEGO_ID` `BASE_ID` INT(11) NOT NULL AFTER `ID`,
	DROP INDEX `JUEGO_ID_R_FK`,
	ADD INDEX `BASE_ID_R_FK` (`BASE_ID`) USING BTREE,
	ADD CONSTRAINT `BASE_ID_R_FK` FOREIGN KEY (`BASE_ID`) REFERENCES `BASE` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;
	
ALTER TABLE `BASE_X_PLATAFORMA`
	ADD COLUMN `FECHA` DATE NULL DEFAULT NULL AFTER `PLATAFORMA_ID`;

ALTER TABLE `BASE_X_PLATAFORMA`
	ADD COLUMN `ID` INT NOT NULL AUTO_INCREMENT FIRST,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`ID`) USING BTREE,
	ADD INDEX `BASE_ID_JXP_FK` (`BASE_ID`);

CREATE TABLE `EDICION` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255) NOT NULL,
	`FECHA` DATE NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `EDICION`
	ADD COLUMN `BASE_ID` INT(11) NOT NULL AFTER `FECHA`,
	ADD COLUMN `PLATAFORMA_ID` INT(11) NULL AFTER `BASE_ID`,
	ADD CONSTRAINT `BASE_ID_E_FK` FOREIGN KEY (`BASE_ID`) REFERENCES `BASE` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	ADD CONSTRAINT `PLATAFORMA_ID_E_FK` FOREIGN KEY (`PLATAFORMA_ID`) REFERENCES `PLATAFORMA` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `EDICION`
	CHANGE COLUMN `NOMBRE` `NOMBRE` VARCHAR(255) NOT NULL AFTER `PLATAFORMA_ID`,
	CHANGE COLUMN `FECHA` `FECHA` DATE NULL DEFAULT NULL AFTER `NOMBRE`;

ALTER TABLE `COLECCION`
	ADD COLUMN `EDICION_ID` INT(11) NULL AFTER `BASE_ID`,
	ADD INDEX `EDICION_ID_C_FK` (`EDICION_ID`),
	ADD CONSTRAINT `EDICION_ID_C_FK` FOREIGN KEY (`EDICION_ID`) REFERENCES `EDICION` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION;
