UPDATE ROM r
JOIN JUEGO j ON j.ID = r.JUEGO_ID
LEFT JOIN IDIOMA i ON i.ID = r.IDIOMA_ID
LEFT JOIN REGION reg ON reg.ID = r.REGION_ID
LEFT JOIN TIPO_ROM t ON t.ID = r.TIPO_ROM_ID
SET r.NOMBRE_ROM = CONCAT(
	j.CODIGO,
	COALESCE(CONCAT('_', i.CORTO), ''),
	COALESCE(CONCAT('_', reg.CORTO), ''),
	COALESCE(CONCAT('.', t.EXTENSION), '')
);